project:
  type: website
  resources: assets
  output-dir: docs

website:
  title: "Nicole Sorensen"
  navbar:
    background: "#B01C33"
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: articles.qmd
        text: Articles
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/nicole-e-sorensen/
        target: _blank
      - icon: github
        href: https://github.com/nicolesorense
        target: _blank
      - icon: file-earmark-pdf-fill
        href: https://nicolesorense.github.io/website/assets/nicole_sorensen_resume_general.pdf
        target: _blank
    google-analytics: "GTM-TL2LTF6L"
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



